# Generated by Django 5.0.7 on 2024-07-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0002_useractivity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useractivity',
            old_name='date',
            new_name='date_joined',
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
