# Generated by Django 5.0.7 on 2024-07-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0004_useractivity_date_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='persian_date_search',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
